### ISSUE TITLE
不太理解为什么要写在useEffect中

### ISSUE THREAD

**Issue by Oliwans** [puxiao/react-hook-tutorial#10]
12章 useRef的基础用法
useRef 使用示例3 子组件中
```
import { useEffect, useState } from "react";

const ChildComponent = ({ funRef }) => {
  const [num, setNum] = useState(0);
  useEffect(() => {
    const doSomething = () => {
      setNum(Math.floor(Math.random() * 100));
    };
    funRef.current = { doSomething }; //在子组件中修改父组件中定义的childFunRef的值
  }, [funRef]);
  return <div>{num}</div>;
};

export default ChildComponent;
```
1.将funRef.current = { doSomething }写在useEffect中，而useEffect后面依赖了变量funRef，这样不会造循环执行吗？
2.doSomething放在useEffect而不是放在子组件中直接创建，每次组件刷新都会从新生成一份doSomething(),这个不太理解

**Comment by puxiao** [comment]
问题1：将funRef.current = { doSomething }写在useEffect中，而useEffect后面依赖了变量funRef，这样不会造循环执行吗？
验证这个问题很简单，你在 useEffect() 中增加一句输出，你就能看出来究竟是否发生了循环执行。

你可以再看看我 那段：**修改 .current 的值并不会触发组件重新渲染**


问题2：doSomething放在useEffect而不是放在子组件中直接创建，每次组件刷新都会从新生成一份doSomething() ?
你要知道 doSomething 是在 useEffect(**() =>{ ... }**) 中的，你看到 doSomething 外层实际上是一个函数(箭头函数)，每次执行该函数，确实相当于重新执行一遍该函数内部的代码，这里面就包括 const doSomething = () =>{}

**Comment by Oliwans** [comment]
1我明白了
2我的意思是为什么doSomething放在useEffect外部的话，每次组件刷新都会从新生成一份doSomething()呢，我写在useEffect外部不行吗？（不过相比较来说确实使用useImperativeHandle这个父组件调用子组件的方法更合适一些）

**Comment by puxiao** [comment]
可能是规则变了，或者是我之前写习惯了，我今天才注意到一个事情：**如果 useEffect() 中使用了某个 useRef 的变量，比如 funRef，是不需要把 funRef 写在 useEffect 的依赖数组 [] 中的**。
