### ISSUE TITLE
咨询一个文章里的问题

### ISSUE THREAD

**Issue by erdong-fe** [puxiao/react-hook-tutorial#18]
博主文章写得挺好，先赞一个，不过我这边有个问题咨询一下，有空可以看看
文章地址：https://github.com/puxiao/react-hook-tutorial/blob/master/01%20React%20Hook%20%E7%AE%80%E4%BB%8B.md
问题描述：文章里面提到了hook的缺点“缺点二：组件数据状态逻辑不能重用、组件之间传值过程复杂”，然后后面又讲了“类组件缺点二：组件之间传值过程复杂、缺点三：复杂场景下代码难以组织在一起Hooks解决方式：通过React内置的useState()函数，可以将不同数据分别从"this.state"中独立拆分出去。降低数据复杂度和可维护性，同时解决类组件缺点三中“内部state数据只能是整体，无法被拆分更细”的问题。”

我的问题是，没有看出来hooks是怎么解决“组件之间传值过程复杂”的问题？

**Comment by puxiao** [comment]
假设有一个用户登陆后提交留言的页面，从表面上看这个页面很简单：一个文本输入框 + 一个提交按钮，但是你试想一下真实的场景，你会发现如此简单的页面背后牵扯了非常多复杂的数据状态。

第一阶段：
1、当前用户是否已登陆
2、当前用户的信息(昵称，角色，是否有留言权限)

第二阶段：
假设已获取上面数据状态，此时用户可以在文本框中输入留言内容了，那么又可能面临下面的需求：
1、我们要求输入内容不能超过 140 字，当用户超出 140 个字后用户可以继续输入，但此时提交按钮不可用，旁边有一个红色文字提醒用户字数超过了，需要用户删减字数后才可以恢复绿色。
2、用户在输入过程中可以使用某些特殊符号进行某些特殊操作，例如 @ 某用户或着 # 添加话题，那么这个过程中需要请求查询相关人信息 和 建议话题标签

第三阶段：
1、当用户点击提交按钮后，发起网络请求，后端接口需要参数：用户id、用户token、留言内容 等等
2、发送请求后当前页面显示一个  loading 圆圈旋转，网络请求成功 loading  圆圈消失
3、当网络发生错误，提交失败，针对不同失败情况进行对应逻辑处理

那么经过我上面描述，你觉得如果这些功能都用一个 react 类组件来实现，是不是比较复杂，涉及好多组件。

这个时候又接到一个新任务：开发一个用户上传某文件的页面

那么你会发现，发布留言和上传文件页面，在很多逻辑上是相同的：
1、判断是否用户是否登陆，获取用户信息
2、网络请求相关
3、全局 loading 动效
...

那这些数据状态和组件 之间数据沟通就比较复杂，就需要单独提取出来，抽离出来，进行解耦。

------- 不过  --------

像上面我描述的场景，真正去开发时，你会发现 react 默认的 hooks 还是不够好，就需要一些基于这些 hooks 二次封装的，例如 某些数据状态库 zustand。
(Vue 是 Pinia)

**Comment by erdong-fe** [comment]
所以是通过状态的抽离来解决数据沟通的问题对吧？
