### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by Phil-Pu** [puxiao/react-hook-tutorial#3]
最近也在学习React Hook，正好搜到了本教程，便简单拜读一遍，收获颇丰。不过教程中还有几个小问题可能需要讨论或者更正：

01 React Hook 简介

1.

> 子组件为了达到修改父组件中的数据状态，通常采用“高阶组件(HOC)”或“父组件暴露修改函数给子组件(render props)”这2种方式。 这2种方式都会让组件变得复杂且降低可复用性。

高阶组件和render props是为了解决代码复用的问题。
实际子组件要修改父组件的数据状态，应该是通过父组件暴露一个回调函数，子组件通过该回调函数传递数据来修改吧？

2.

> 复杂场景下，比如数据获取(dade fetching)和事件订阅(event listeners)，相关代码难以组织在一起。

dade fetching应为data fetching。

03 useState高级用法

1.

> 通过React官方文档可以知道，当使用 setXxx 赋值时，Hook会使用Object.is()来对比当前值和新值，结果为true则不渲染，结果为flash就会重新渲染。

flash应为false。

06 useContext基础用法

1.

> 请注意传值必须使用value={obj}这种形式；

Context传值时，value后面不一定必须是对象，也可以是字符串等原始类型值。

2.

> 在类组件中除了<XxxContext.Consumer>标签，还有另外一种获取共享数据方式：static xxx = XxxContext; 但是这种形式在函数组件中无法使用。

在类组件中，一般是指定类组件的静态属性contentType，这样在类中可以直接用this.context消费该Context的值，而不是任意一个静态属性。

08 useReducer基础用法

1.

> EventEimtter

是否是“EventEmitter”？

**Comment by puxiao** [comment]
感谢你的细心指正，确实好几处都是手误拼写错了。
如果是全局数据状态，我更推荐你使用 Recoil 。

**Comment by puxiao** [comment]
在我的实际开发中，使用的仅仅是：useState、useEffect、useRef，也就是说这 3 个就足够应对日常开发了 。
极少情况下会使用 useContent。

我实际项目中几乎没有用过 useCallback、useMemo、useReducer...
因为这些所谓的性能优化 hooks 心智负担很重，并且它会给你一种错觉：你在优化性能，但实际上很有可能让你的代码变得臃肿，难以理解。
我们应该充分相信 React 本身已经在内部帮我们做了非常多的性能优化决策，所以没有必要自己过分去执着去用它们。

并且我今天下午还遇到了一个 “陷阱”，在我的组件内部定义了一个其他地方使用的回调函数，该回调函数内部使用了组件参数中的一个变量，结果就产生了闭包，在实际执行时内部得不到那个参数。
最开始我想尝试将那个函数使用 useCallback，结果不行，最终解决方式是 使用 useRef 来定义函数中用到的变量。每次组件参数发生变化时 useEffect 中通过 xxxRef.current = xxx 来修改“变量”的值。
这样就解决了 闭包 问题，在那个函数中可以找到(更新) 所需的变量。

**Comment by puxiao** [comment]
@Phil-Pu  LGTM
