### ISSUE TITLE
03 useState 高级用法中的一点小问题

### ISSUE THREAD

**Issue by OuYangHuaQing** [puxiao/react-hook-tutorial#6]
**这里应该是深拷贝吧**

![QQ图片20220701104644.png](https://s2.loli.net/2022/07/01/3BbMrPX157tChQV.png)

**Comment by puxiao** [comment]
从我举的示例上看，由于 name 和 age 的值类型分别为 字符串和数字，这 2 种简单类型的解构确实是在内存中 重新创建 了一份，要说是 “深拷贝” 也对。

不过在 JS 中，从更广义的角度来看，解构赋值 得到的新对象组成的对象，究竟是深拷贝还是浅拷贝 取决于 属性值的类型是什么，如果属性值不是简单类型，而是 数组、对象 等，则执行的是浅拷贝。
