### ISSUE TITLE
usecallback

### ISSUE THREAD

**Issue by buslightyear** [puxiao/react-hook-tutorial#7]
博主，10.useCallback那篇我有个疑问。
文章末尾那个案例，提到：只要依赖变量不发生变化，那么重新渲染时就可以一直使用之前创建的那个函数，达到阻止本次渲染。我的理解是clickHandler01 和clickHandler02着两个函数不用重新渲染，但是跟按钮没关系。
因为不是还有这个规则吗：默认情况下如果父组件重新渲染，那么该父组件下的所有子组件都会随着父级的重新渲染而重新渲染。
所以我的疑问是为啥点击一个按钮不会让另外一个按钮重新渲染

**Comment by puxiao** [comment]
实话实说，我个人写了一年多的 React，我就没用过 useCallback、useMemo。
因为实际情况是我没遇到过 “需要你去做极致性能优化” 的场景需求。
React 18 异步可中断更新 + 并行机制，对于一般性的开发场景已经完全不需要你 “人工” 特意去做性能优化。

> Vue作者尤雨溪说过一段话，大意是：React会给前端开发者一种错觉，让他们误以为自己在做性能优化，从而达到一种精神上的满足和自豪。

我给你的建议是：除了我的文章，你可以去掘金上面搜一下，目前不是2年前我学习 React 中文资料少的情况了，现在特别多的教程。 多看几个人的教程，多几个视角，加上自己的体会理解，你就学成了。

另外，我推荐你去B站看一下 卡颂 半年前 录的一个关于 React 性能优化的视频，实话实说 我当时看完了内心高呼 ：我~，还可以这样搞。

React性能优化，你需要知道的一切：
https://www.bilibili.com/video/BV1Yr4y1J7oc/

**Comment by Oliwans** [comment]
@buslightyear 我理解应该是React.memo()包裹的原因，使得React底层判断当前的useCallback的依赖变量没有发生变化后，不必去渲染由React.memo()包裹的组件，所以useCallback和React.memo()必须结合使用才能到达一个性能优化的效果。
